@url_dev=http://localhost:3055/v1/api

### login
POST {{url_dev}}/user/login
Content-Type: application/json
x-api-key: 2f9ab30e22b0312538ce881e36527a08cd5c88e20db07249aad97565ad16912e47cd83d4c4526d1af807c7cd6d49d215451896e2a301bdbc55912b6a8d048708

{
    "email": "haidngpham112000+005@gmail.com",
    "password": "pass1234"
}

### signup
POST {{url_dev}}/user/signup
Content-Type: application/json
x-api-key: 

{
    "name": "haidngpham112000+005",
    "email": "haidngpham112000+005@gmail.com",
    "password": "pass1234"
}

### logout
POST {{url_dev}}/user/logout
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 


### handleRefreshTokenV2
POST {{url_dev}}/user/handleRefreshToken
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
x-rtoken-id:  
