@url_dev=http://localhost:3055/v1/api

### find all posts
GET {{url_dev}}/post
Content-Type: application/json
x-api-key: 

### find post 
GET {{url_dev}}/post/67204f2150eb3779aba3e0c5
Content-Type: application/json
x-api-key: 

### search posts by user
GET {{url_dev}}/post/search/MANTRA
Content-Type: application/json
x-api-key: 

### find all user's draft posts
GET {{url_dev}}/post/drafts/all
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 

### find all user's published posts
GET {{url_dev}}/post/published/all
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 

### create post
POST {{url_dev}}/post
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 

{
    "title": "Cap doi dep nhat OK",
    "media": "This is a video link",
    "summary": "Cap doi dep nhat rat ok",
    "content":"okokokokokokokokokok",
    "price": "60",
    "topic": "Movie",
    "attributes": {
        "movieName": "Cap doi dep nhat",
        "director": "HKT"
    }
}

# {
#     "title": "Giay ghi chu tam nguyen OK",
#     "media": "This is a video link",
#     "summary": "Giay ghi chu tam nguyen xai rat ok",
#     "content":"okokokokokokokokokok",
#     "price": "30",
#     "topic": "Tech",
#     "attributes": {
#         "productName": "Giay ghi chu tam nguyen",
#         "inventor": "unknown"
#     }
# }

# {
#     "title": "Do u liek OIK",
#     "media": "This is a video link",
#     "summary": "OIK is OK",
#     "content":"OIK is OKOIK is OK",
#     "price": "100",
#     "topic": "Music",
#     "attributes": {
#         "musicName": "OIK",
#         "singer": "163Brace"
#     }
# }

### publish post by user
POST {{url_dev}}/post/publish/6722e7e1b14316be70bd2269
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 


### unpublish post by user
POST {{url_dev}}/post/unpublish/671cc32e2bf16b546abfad74
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 


### update post
PATCH {{url_dev}}/post/67204f2150eb3779aba3e0c5
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 

{
    "title": "Do u leik OIK",
    "price": null,
    "topic": "Music",
    "attributes": {
        "musicName": null,
        "singer": "163Brace nene"
    }
}