@url_dev=http://localhost:3055/v1/api

### find all posts
GET {{url_dev}}/post
Content-Type: application/json
x-api-key: 

### find post 
GET {{url_dev}}/post/67204f2150eb3779aba3e0c5
Content-Type: application/json
x-api-key: 

### search posts by user
GET {{url_dev}}/post/search/MANTRA
Content-Type: application/json
x-api-key: 

### find all user's draft posts
GET {{url_dev}}/post/drafts/all
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 

### find all user's published posts
GET {{url_dev}}/post/published/all
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 

### create post
POST {{url_dev}}/post
Content-Type: application/json
x-api-key: 
x-client-id: 6723989527f9a785bb260f26
authorization: 

# {
#     "title": "Normal no more is new trending",
#     "media": "This is a video link",
#     "summary": "Normal no more rat ok",
#     "content":"Normal no more okokokokokokokokokok",
#     "price": 15,
#     "topic": "Movie",
#     "attributes": {
#         "movieName": "Normal no more",
#         "director": "Black Shadow"
#     }
# }

{
    "title": "Poker Face OK",
    "media": "This is a video link",
    "summary": "Poker Face xai rat ok",
    "content":"Poker Face okokokokokokokokokok",
    "price": 17,
    "topic": "Tech",
    "attributes": {
        "productName": "Poker Face",
        "inventor": "Lady Gaga"
    }
}

# {
#     "title": "Take You To Hell is crazy",
#     "media": "This is a video link",
#     "summary": "Take You To Hell is OK",
#     "content":"Take You To Hell is more than OK",
#     "price": 50,
#     "topic": "Music",
#     "attributes": {
#         "musicName": "Take You To Hell",
#         "singer": "Ava Max"
#     }
# }

### publish post by user
POST {{url_dev}}/post/publish/6722e7e1b14316be70bd2269
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 


### unpublish post by user
POST {{url_dev}}/post/unpublish/671cc32e2bf16b546abfad74
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 


### update post
PATCH {{url_dev}}/post/67204f2150eb3779aba3e0c5
Content-Type: application/json
x-api-key: 
x-client-id: 671caf1631df2ea7cb9529ec
authorization: 

{
    "title": "Do u leik OIK",
    "price": null,
    "topic": "Music",
    "attributes": {
        "musicName": null,
        "singer": "163Brace nene"
    }
}